### PR TITLE
Populate Users/Radio Buttons

### PR DESCRIPTION
**Pull request by rarceneaux**
added users data to onload function and called radioButtonBuilder to add additional users after the 5 sample msg data

### CODE REVIEW

**Comment by shanedwilson** [comment]
I get an uncaught reference error when trying to load the page.

**Comment by Waysidetester** [comment]
I don't see the users populate in the browser. I also don't see the nav bar. Have you merged your working branch with the updated master branch?

image

**Comment by rarceneaux** [comment]
I did the following:
-git fetch all
-git checkout master
-git pull origin master
-git merge master
-git checkout new branch

**Comment by shanedwilson** [comment]
Looks closer. On my machine, the buttons are mostly behind the nav-bar. Try adding ```class=mt-5``` to your user div. That's bootstrap styling for margin-top.

**Comment by rarceneaux** [comment]
fixed radio button view --add class mt-5 to user div
screen shot 2018-10-11 at 5 54 09 am

**Comment by shanedwilson** [comment]
👍. Looks good.

**Pull request closed without merging**
