### PR TITLE
fixed nav

### PR DESCRIPTION
**Pull request by westmary48**

### CODE REVIEW

**Comment by Waysidetester** [comment]
When I am looking at the page, the nav is covering the messages text. I have master up to date and i am on your branch. Can you determine if this is an issue with the HTML or the event listeners? Did your or someone else add the event listeners?

image

**Comment by shanedwilson** [comment]
dark theme function is fixed! I am, however getting the same thing as Dylan with the message text. If I set my zoom to 80%, it looks like your screenshot, Mary.  Regardless, it seems like we should put the h1 inside the chat-container div.

**Comment by shanedwilson** [comment]
👍

**Comment by Waysidetester** [comment]
👍

**Pull request merged**
